# Generated by Django 4.1.2 on 2022-11-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_alter_expenses_date_alter_listing_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='shipped',
            field=models.BooleanField(default=False),
        ),
    ]
