# Generated by Django 4.1.3 on 2022-11-20 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_userprofile_facebook_userprofile_github_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
