# Generated by Django 4.1.3 on 2022-11-20 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_listing_rmbg_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='rmbg_img',
        ),
    ]
