# Generated by Django 4.1.3 on 2022-11-20 17:05

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_remove_listing_rmbg_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='upload/placeholder.png', force_format=None, keep_meta=True, quality=100, scale=None, size=[500, 500], upload_to='upload/'),
        ),
    ]
