# Generated by Django 4.1.3 on 2022-11-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_listing_rmbg_image_alter_listing_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='rmbg_image',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='upload/placeholder.png', null=True, upload_to='upload/category/'),
        ),
    ]
