# Generated by Django 4.1.3 on 2022-11-25 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0027_remove_listing_rmbg_image_category_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-id']},
        ),
    ]
