# Generated by Django 4.1.3 on 2022-11-26 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0029_listing_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
