# Generated by Django 4.1.3 on 2022-11-26 03:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0030_listing_reported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1024, null=True),
        ),
    ]
