# Generated by Django 4.1.2 on 2022-10-30 04:47

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 30, 4, 47, 24, 648007, tzinfo=datetime.timezone.utc)),
        ),
    ]
