# Generated by Django 4.1.2 on 2022-10-30 04:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_alter_email_body_alter_email_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 30, 4, 54, 47, 89177, tzinfo=datetime.timezone.utc)),
        ),
    ]
